#!/bin/bash

BASEDIR=/home/ssnyde11/scratch/
GENOME_DIR=genomes/
GENOME_FILE=PA42.4.1.fasta
GENOME_GFF=PA42.4.0.gff
RNAfile=${BASEDIR}/${GENOME_DIR}/Dpul-rDNA.fa
  
EXPERIMENT=daphnia_stripe_2
SAMPLE=Dpul_obt_STRIPE
fastqDIR=${BASEDIR}/${EXPERIMENT}/fastqdir/
SCRIPTS=${BASEDIR}/${EXPERIMENT}/${SAMPLE}/scripts/

BWA=/packages/spack/linux-centos7-x86_64/gcc-4.8.5/bwa-0.7.17-fusrahsomx5s4f64jk455gpi7i6xgaza/bin/bwa
PYTHON3=/usr/bin/python3
RSCRIPT=/packages/7x/r/3.5.2/bin/Rscript
SAMTOOLS=/packages/7x/samtools/1.8/bin/samtools
SRATOOLKIT=/packages/7x/sratoolkit/2.8.0/bin/
TAGDUST=~/genome_analysis/tagdust-2.33/src/tagdust
TRIMMOMATIC=/packages/7x/trimmomatic/0.33/trimmomatic.jar
TruSeq2PE=${BASEDIR}/${GENOME_DIR}/DpSTRIPE-PE.fa
THREADS=10

R_PROFILE_USER=""
